### ISSUE TITLE
在人脸认证页面.dialog弹出之前退出认证页面.BadTokenException

### ISSUE THREAD

**Issue by liuxvdong031** [AnyLifeZLB/FaceVerificationSDK#3]
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@b8a959a is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1141)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:111)
        at android.app.Dialog.show(Dialog.java:342)
        at android.app.AlertDialog$Builder.show(AlertDialog.java:1156)
        at com.faceVerify.test.VerifyActivity.lambda$showAliveDetectTips$1$com-faceVerify-test-VerifyActivity(VerifyActivity.java:158)
        at com.faceVerify.test.VerifyActivity$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at android.app.Activity.runOnUiThread(Activity.java:7199)
        at com.faceVerify.test.VerifyActivity.showAliveDetectTips(VerifyActivity.java:146)
        at com.faceVerify.test.VerifyActivity.access$000(VerifyActivity.java:51)
        at com.faceVerify.test.VerifyActivity$1.onProcessTips(VerifyActivity.java:131)
        at com.AI.FaceVerify.verify.b$a.onFinish(FaceDetectorProcess.java:2)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8087)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by AnyLifeZLB** [comment]
1.1.0 get start.
