### ISSUE TITLE
和room冲突

### ISSUE THREAD

**Issue by yzc90912** [AnyLifeZLB/FaceVerificationSDK#32]
java.lang.RuntimeException: Cannot find implementation for .db.AppDatabase. AppDatabase_Impl does not exist

**Comment by AnyLifeZLB** [comment]
Log 有点少，能否提供更多的信息，谢谢

**Comment by yzc90912** [comment]
如果直接使用库中的room 报错
Process: com.jnet.softservice, PID: 24858
                                                                                                    java.lang.RuntimeException: Cannot find implementation for com.jnet.softservice.db.AppDatabase. AppDatabase_Impl does not exist
                                                                                                    	at androidx.room.Room.getGeneratedImplementation(Room.kt:58)
                                                                                                    	at androidx.room.RoomDatabase$Builder.build(RoomDatabase.kt:1357)
                                                                                                    	at com.jnet.softservice.db.AppDatabase$Companion.getInstance(AppDatabase.kt:54)
                                                                                                    	at com.jnet.softservice.ui.activity.mine.LoginActivity.lambda$onCreate$0$com-jnet-softservice-ui-activity-mine-LoginActivity(LoginActivity.java:228)
                                                                                                    	at com.jnet.softservice.ui.activity.mine.LoginActivity$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-01-16 15:30:21.104 24858-24909 OpenGLRenderer          com.jnet.softservice                 E  Unable to match the desired swap behavior.

**Comment by AnyLifeZLB** [comment]
尝试升级SDK 1.8.2
