### ISSUE TITLE
1:1识别创建BaseImageDispose失败

### ISSUE THREAD

**Issue by 1996cy** [AnyLifeZLB/FaceVerificationSDK#40]
问题场景描述

在1:1添加人脸底片的时候, 创建BaseImageDispose报错, demo可以运行, 我把demo的页面拿过来用, 在打开添加底片的页面就报错, 不知道是不是我漏了什么步骤

手机品牌，型号

平板

Android 系统版本

Android 9

错误信息

 Process: com.android.ceshi, PID: 6444
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.ceshi/com.android.ceshi.AddFaceImageActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String Object.Companion.ILil()' on a null object reference
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
 	at android.os.Handler.dispatchMessage(Handler.java:106)
 	at android.os.Looper.loop(Looper.java:193)
 	at android.app.ActivityThread.main(ActivityThread.java:6718)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String Object.Companion.ILil()' on a null object reference
 	at I丨iL.Companion.Companion(SourceFile:13)
 	at com.ai.face.base.baseImage.BaseImageDispose.<init>(SourceFile:46)
 	at com.ai.face.base.baseImage.BaseImageDispose.<init>(SourceFile:4)
 	at com.ai.face.base.baseImage.BaseImageDispose.<init>(SourceFile:1)
 	at com.android.ceshi.AddFaceImageActivity.onCreate(AddFaceImageActivity.java:78)
 	at android.app.Activity.performCreate(Activity.java:7171)
 	at android.app.Activity.performCreate(Activity.java:7162)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086) 
 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
 	at android.os.Handler.dispatchMessage(Handler.java:106) 
 	at android.os.Looper.loop(Looper.java:193) 
 	at android.app.ActivityThread.main(ActivityThread.java:6718) 
 	at java.lang.reflect.Method.invoke(Native Method) 
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by AnyLifeZLB** [comment]
直接copy demo 的吗？如果有改动发我代码 @1996cy

**Comment by 1996cy** [comment]
没有改动代码, 我试着在你的demo项目里修改使用, 发现改了包名就无法创建, 是有什么权限控制吗, 我仅是使用1:1的, 且没有开活体检测

**Comment by AnyLifeZLB** [comment]
@1996cy 不好意思，好久没关注，请更新到最新版本1.8.26 试试。更改包名后请Clean 工程，invalidate cache.重启AS

还有问题 @我

**Comment by AnyLifeZLB** [comment]
@1996cy 不好意思，是我们的问题，试用版本确实有问题。1.8.49 修复了此问题
